load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
  name = "p1",
  srcs = ["p1.cc"],
  deps = [
    "//projecteuler/solutions:library",
  ],
)

cc_binary(
  name = "p2",
  srcs = ["p2.cc"],
  deps = [
    "//projecteuler/solutions:library",
  ],
)

cc_binary(
  name = "p3",
  srcs = ["p3.cc"],
  deps = [
    "//projecteuler/solutions:library",
  ],
)
